---
- name: Wait for cassandra to start
  wait_for:
    host: "{{ cassandra_address }}"
    port: "{{ cassandra_port }}"

- name: Copy authentication script
  template:
    src: auth.sh.j2
    dest: /root/cassandra_auth.sh
    mode: 0755
  register: auth

- name: Run auth script
  command: /root/cassandra_auth.sh
  when: auth | changed
