---
- name: Make sure dirs exist
  file:
    path: "{{ item }}"
    state: directory
    group: docker
    mode: 0777
  with_items:
    - "/var/lib/docker/volumes/{{ cassandra_root_dir }}/_data"
    - "/var/lib/docker/volumes/{{ cassandra_data_dir }}/_data/"
    - "/var/lib/docker/volumes/{{ cassandra_java_dir }}/_data/"
  register: dir_creation

- name: Configure cassandra
  template:
    src: cassandra.yaml.j2
    dest: "/var/lib/docker/volumes/{{ cassandra_root_dir }}/_data/cassandra.yaml"
  changed_when: false

- name: Enable metrics
  lineinfile:
    dest: /var/lib/docker/volumes/{{ cassandra_root_dir }}/_data/cassandra-env.sh
    line: JVM_OPTS="$JVM_OPTS -javaagent:/usr/share/java/jmx_prometheus_javaagent-{{ cassandra_jmx_exporter_version }}.jar={{ cassandra_jmx_exporter_port }}:{{ cassandra_docker_root_dir }}/cassandra.yaml"
  when: cassandra_metrics