---
- name: Download and run Cassandra instance
  docker_container:
    name: cassandra
    image: "cassandra:{{ cassandra_version }}"
    state: present
    restart_policy: unless-stopped
    network_mode: host
#    ports:
#      - "7000:7000"
#      - "9042:9042"
    volumes:
      - "cass-data-dir:{{ cassandra_docker_data_dir }}:rw"
      - "cass-root-dir:{{ cassandra_docker_root_dir }}:rw"
      - "cass-java-dir:{{ cassandra_docker_java_dir }}:rw"