---
- name: Set cassandra address
  set_fact:
    cassandra_address: "{{ hostvars[inventory_hostname]['ansible_' + cassandra_interface]['ipv4']['address'] }}"
  when: cassandra_address is undefined

- name: Check if cluster has odd number of hosts
  fail:
    msg: "The number of hosts in inventory MUST NOT be even"
  when: groups[cassandra_hosts_group] | length is even

- include: install.yml

- include: auth.yml
  when:
    - cassandra_auth
    - cassandra_users | length > 0