---
- name: Set cassandra address
  set_fact:
    cassandra_address: "{{ hostvars[inventory_hostname]['ansible_' + cassandra_interface]['ipv4']['address'] }}"
  when: cassandra_address is undefined

- name: debug
  debug:
    var: hostvars[inventory_hostname]

- include: install.yml

- include: tests.yml
  when: cassandra_tests