---
- name: Ensure directory exists
  file:
    path: "/etc/telegraf/telegraf.d"
    state: directory

- name: Create telegraf plugin config
  template:
    src: cassandra_telegraf.conf.j2
    dest: /etc/telegraf/telegraf.d/cassandra.conf

